#!/bin/sh

set -e

basedir=$(dirname $0)

(
	cd $basedir && \
		autoreconf -ivf && \
		$basedir/configure $@ && \
		make -C $basedir fetch
)

echo "###"
echo "### You can now run configure"
echo "###"

exit 0
